# Generated by Django 5.2.13 on 2026-04-17 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
