# Generated by Django 5.2.14 on 2026-05-13 12:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_settings_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="quiet_hours_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="quiet_hours_end",
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name="user",
            name="quiet_hours_start",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
