# Generated by Django 5.2.11 on 2026-02-27 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="stock_usage",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Units deducted from stock per entry",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
