# Generated by Django 5.2.11 on 2026-03-01 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_routineentry_consumed_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
