# Generated by Django 5.2.12 on 2026-03-04 08:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0005_stockgroup_stock_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockConsumption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "consumed_lots",
                    models.JSONField(
                        blank=True, default=list, help_text="Lots consumed: [{lot_number, expiry_date, quantity}]"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="consumptions", to="routines.stock"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
