# Generated by Django 5.2.12 on 2026-03-05 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0006_stockconsumption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="shared_with",
            field=models.ManyToManyField(blank=True, related_name="shared_routines", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="routineentry",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="shared_with",
            field=models.ManyToManyField(blank=True, related_name="shared_stocks", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="stockconsumption",
            name="consumed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_consumptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
