# Generated by Django 5.2.12 on 2026-03-05 22:24

from django.db import migrations


def backfill_completed_by(apps, schema_editor):
    RoutineEntry = apps.get_model("routines", "RoutineEntry")
    for entry in RoutineEntry.objects.filter(completed_by__isnull=True).select_related("routine"):
        entry.completed_by = entry.routine.user
        entry.save(update_fields=["completed_by"])


def backfill_consumed_by(apps, schema_editor):
    StockConsumption = apps.get_model("routines", "StockConsumption")
    for consumption in StockConsumption.objects.filter(consumed_by__isnull=True).select_related("stock"):
        consumption.consumed_by = consumption.stock.user
        consumption.save(update_fields=["consumed_by"])


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0007_routine_shared_with_routineentry_completed_by_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_completed_by, migrations.RunPython.noop),
        migrations.RunPython(backfill_consumed_by, migrations.RunPython.noop),
    ]
