# Generated by Django 5.2.13 on 2026-04-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0008_backfill_completed_by_consumed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stockconsumption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
