# Generated by Django 5.2.13 on 2026-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0009_routineentry_updated_at_stockconsumption_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineentry",
            name="client_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockconsumption",
            name="client_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
