# Generated by Django 5.2.14 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0012_backfill_client_created_at_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="reminder_interval_minutes",
            field=models.PositiveIntegerField(
                choices=[(60, "1 hour"), (120, "2 hours"), (240, "4 hours"), (480, "8 hours")],
                default=120,
                help_text="Minutes between reminders when mode is 'intensive'",
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="reminder_mode",
            field=models.CharField(
                choices=[("intensive", "Intensive"), ("daily", "Daily")],
                default="intensive",
                help_text="'intensive' = repeating reminders; 'daily' = covered by heads-up only",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="respect_quiet_hours",
            field=models.BooleanField(default=True),
        ),
    ]
