# Generated by Django 5.2.15 on 2026-08-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0014_add_interval_phases"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklot",
            name="raw_scan",
            field=models.TextField(blank=True, help_text="Raw decoded barcode payload, kept for traceability."),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="GS1 AI 21 — serial of the physical pack. Empty for hand-entered lots.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial_number", ""), _negated=True),
                fields=("stock", "serial_number"),
                name="unique_serial_per_stock",
            ),
        ),
    ]
