# Generated by Django 5.2.17 on 2026-08-06 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0015_add_stocklot_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="default_lot_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantity to prefill when adding a lot. Null when not yet known.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="gtin",
            field=models.CharField(
                blank=True, help_text="GS1 AI 01 — product code read from the pack. Empty when unknown.", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="stocklot",
            name="raw_scan",
            field=models.TextField(
                blank=True,
                help_text="Raw decoded barcode payload. Kept for traceability and as the source of product identity (GTIN).",
            ),
        ),
    ]
