import { publishRemoteVersion } from '../contexts/appVersionBridge'
import { noteServerError, setReachable } from '../offline/reachability'
import { ConflictError, OfflineError } from './errors'

const BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api'

const MUTATION_METHODS = new Set(['POST', 'PATCH', 'PUT', 'DELETE'])

// Mutex: if a token refresh is already in progress, subsequent 401s wait
// for the same promise instead of firing duplicate refresh requests.
let refreshPromise = null

async function request(path, options = {}, retry = true) {
  const method = (options.method || 'GET').toUpperCase()
  const token = localStorage.getItem('access_token')

  const headers = {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...options.headers,
  }

  // Idempotency-Key is pre-generated by the mutation helpers (post/patch/
  // delete) and passed via `options.idempotencyKey` so a retry after a 401
  // token refresh re-sends the SAME key — guaranteed at-most-once semantics.
  if (MUTATION_METHODS.has(method) && options.idempotencyKey) {
    headers['Idempotency-Key'] = options.idempotencyKey
  }

  // Optimistic concurrency: when the caller knows the `updated_at` it read
  // from the server, pass it as `options.ifUnmodifiedSince` and we translate
  // to the HTTP-date header the backend's OptimisticLockingMixin expects.
  if ((method === 'PATCH' || method === 'DELETE' || method === 'PUT') && options.ifUnmodifiedSince) {
    headers['If-Unmodified-Since'] = new Date(options.ifUnmodifiedSince).toUTCString()
  }

  // Strip the client-only options before forwarding to fetch so they don't
  // leak into RequestInit.
  const { idempotencyKey: _k, ifUnmodifiedSince: _s, ...fetchOptions } = options

  let res
  try {
    res = await fetch(`${BASE_URL}${path}`, {
      ...fetchOptions,
      method,
      headers,
    })
  } catch (err) {
    // `fetch` rejects for three reasons: a genuine network failure, a
    // CORS violation, or an explicit `AbortController.abort()` by the
    // caller. Keep the two cases separate:
    //   - `AbortError` means the caller (typically the sync worker, T065)
    //     cancelled on purpose — re-throw verbatim so they can react.
    //   - Anything else is treated as offline: flip the reachability
    //     signal (boots the health poll, T057) and wrap in OfflineError
    //     so the offline queue can enqueue the mutation.
    if (err?.name === 'AbortError') throw err
    setReachable(false)
    throw new OfflineError(err)
  }
  // Gateway-level errors mean the proxy reached us but the upstream
  // (Django container) is not responding. Treat this as offline so the
  // existing infrastructure (banner, queue, SW cache fallback) kicks in.
  // `noteServerError()` only flips reachability after SERVER_ERROR_THRESHOLD
  // consecutive hits without a 2xx — prevents banner flicker during fast
  // upstream restarts. 500 is intentionally NOT in this set: it usually
  // signals a bug on a single endpoint, not "everything is down".
  if (res.status === 502 || res.status === 503 || res.status === 504) {
    noteServerError()
    throw new OfflineError(new Error(`Gateway ${res.status}`))
  }
  // Any other HTTP response (2xx, 3xx, 4xx, 500) proves the backend
  // itself is reachable and answering.
  setReachable(true)

  // Surface the backend's version (X-App-Version, set by the
  // AppVersionHeaderMiddleware) to the AppVersionProvider via the
  // imperative bridge. The provider compares it to VITE_APP_VERSION
  // and the AutoUpdater triggers a silent reload on the next safe
  // navigation when they diverge. Header is absent in tests that
  // don't emit it — silently skip in that case.
  //
  // Skip when the response was served from the SW's gateway-error
  // fallback (X-From-Cache: 1): the cached X-App-Version may belong
  // to a previous deploy, and feeding it to the AppVersionProvider
  // would trigger a spurious forceReload() during a backend outage.
  const fromCache = res.headers?.get?.('X-From-Cache')
  if (!fromCache) {
    const remoteVersion = res.headers?.get?.('X-App-Version')
    if (remoteVersion) publishRemoteVersion(remoteVersion)
  }

  if (res.status === 401 && retry) {
    const refreshed = await tryRefreshToken()
    if (refreshed) {
      return request(path, options, false)
    }
    localStorage.removeItem('access_token')
    localStorage.removeItem('refresh_token')
    window.location.href = '/login'
    return res
  }

  if (res.status === 412) {
    const body = await res.json().catch(() => ({}))
    throw new ConflictError(body?.current)
  }

  return res
}

async function tryRefreshToken() {
  if (refreshPromise) return refreshPromise

  refreshPromise = doRefresh()
  try {
    return await refreshPromise
  } finally {
    refreshPromise = null
  }
}

async function doRefresh() {
  const refresh = localStorage.getItem('refresh_token')
  if (!refresh) return false

  const res = await fetch(`${BASE_URL}/auth/refresh/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refresh }),
  })

  if (!res.ok) return false

  const { access, refresh: newRefresh } = await res.json()
  localStorage.setItem('access_token', access)
  if (newRefresh) localStorage.setItem('refresh_token', newRefresh)
  return true
}

function makeMutationOptions(method, body, opts) {
  const idempotencyKey = opts.idempotencyKey ?? opts.headers?.['Idempotency-Key'] ?? crypto.randomUUID()
  return {
    ...opts,
    method,
    body: body !== undefined ? JSON.stringify(body) : undefined,
    idempotencyKey,
  }
}

export const api = {
  get: (path, opts = {}) => request(path, { ...opts, method: 'GET' }),
  post: (path, body, opts = {}) => request(path, makeMutationOptions('POST', body, opts)),
  patch: (path, body, opts = {}) => request(path, makeMutationOptions('PATCH', body, opts)),
  delete: (path, body, opts = {}) => request(path, makeMutationOptions('DELETE', body, opts)),
}

export { BASE_URL }
