import { clear as idbClear, createStore, del, entries, get, set } from 'idb-keyval'

/**
 * Persistent FIFO queue of mutations waiting to be replayed when the browser
 * recovers connectivity. Each entry is keyed by its Idempotency-Key (a UUIDv4
 * generated by useOfflineMutation and reused verbatim when the sync worker
 * re-issues the request — guaranteed at-most-once on the server).
 *
 * Entry shape (all fields persisted in IndexedDB):
 *   {
 *     id: string (UUID == Idempotency-Key),
 *     method: 'POST' | 'PATCH' | 'DELETE' | 'PUT',
 *     endpoint: string (API path, relative to BASE_URL),
 *     body: any | null,
 *     resourceKey: string | null ('routine:5', 'stock:3:lot:7', …),
 *     ifUnmodifiedSince: string | null (ISO timestamp),
 *     createdAt: string (ISO timestamp),
 *     status: 'pending' | 'syncing' | 'error' | 'conflict',
 *     retryCount: number (default 0, incremented by `markRetryPending`),
 *     nextAttemptAt: string | null (ISO timestamp; sync worker skips entries
 *         whose scheduled attempt is still in the future — T064 backoff),
 *     errorMessage?: string,
 *     conflictCurrent?: any,
 *   }
 */

const STORE = createStore('nudge-offline', 'mutations')

// Simple pub/sub so the UI (PendingBadge, SyncStatusBadge, ConflictOrchestrator
// in T026) can react to every write. A native EventTarget is enough for a
// single-tab queue; switching to a BroadcastChannel would be the upgrade path
// for cross-tab scenarios, out of scope here.
const events = new EventTarget()

// Abort-controller registry (T065). The sync worker registers a controller
// while a request is in flight so `remove(id)` can cancel the in-flight
// fetch — discarding an entry from the PendingBadge while it is `syncing`
// would otherwise leave the server processing a request the UI already
// dropped.
const abortControllers = new Map()

export function registerAbortController(id, controller) {
  abortControllers.set(id, controller)
}

export function clearAbortController(id) {
  abortControllers.delete(id)
}

function emit() {
  events.dispatchEvent(new Event('change'))
}

export function subscribe(listener) {
  events.addEventListener('change', listener)
  return () => events.removeEventListener('change', listener)
}

export async function enqueue(entry) {
  if (!entry?.id) throw new Error('enqueue: entry.id is required (use the Idempotency-Key)')
  const normalised = {
    retryCount: 0,
    nextAttemptAt: null,
    ...entry,
  }
  await set(entry.id, normalised, STORE)
  emit()
}

export async function list() {
  const rows = await entries(STORE)
  return rows.map(([, v]) => v).sort((a, b) => a.createdAt.localeCompare(b.createdAt))
}

async function patchStatus(id, patch) {
  const existing = await get(id, STORE)
  if (!existing) return null
  const next = { ...existing, ...patch }
  await set(id, next, STORE)
  emit()
  return next
}

export function markSyncing(id) {
  return patchStatus(id, { status: 'syncing', errorMessage: undefined })
}

export function markPending(id) {
  return patchStatus(id, { status: 'pending', errorMessage: undefined })
}

/**
 * Reschedules an entry for a future retry. Increments `retryCount` and
 * stamps `nextAttemptAt` so `processQueue` skips it until the timer fires.
 * Used by the sync worker's exponential backoff on 408/429/5xx (T064).
 */
export async function markRetryPending(id, delayMs) {
  const existing = await get(id, STORE)
  if (!existing) return null
  const next = {
    ...existing,
    status: 'pending',
    errorMessage: undefined,
    retryCount: (existing.retryCount ?? 0) + 1,
    nextAttemptAt: new Date(Date.now() + Math.max(0, delayMs)).toISOString(),
  }
  await set(id, next, STORE)
  emit()
  return next
}

export function markError(id, errorMessage) {
  return patchStatus(id, { status: 'error', errorMessage })
}

export function markConflict(id, conflictCurrent) {
  return patchStatus(id, { status: 'conflict', conflictCurrent })
}

export async function remove(id) {
  const controller = abortControllers.get(id)
  if (controller) {
    controller.abort()
    abortControllers.delete(id)
  }
  await del(id, STORE)
  emit()
}

export async function clear() {
  await idbClear(STORE)
  emit()
}
