import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'

// Remove caches from older Workbox versions that are no longer needed.
cleanupOutdatedCaches()

// Precache all assets generated by Vite (injected by vite-plugin-pwa at build time).
precacheAndRoute(self.__WB_MANIFEST)

// ── Push notifications ────────────────────────────────────────────────────────

self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {}
  const title = data.title ?? 'Nudge'
  const options = {
    body: data.body ?? '',
    icon: '/icons/pwa-192x192.png',
    badge: '/icons/badge.svg',
    data: data.data ?? {},
    actions: data.actions ?? [],
  }
  event.waitUntil(self.registration.showNotification(title, options))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const routineId = event.notification.data?.routine_id
  const url = event.action === 'mark-done' && routineId
    ? `/routines/${routineId}?action=mark-done`
    : routineId ? `/routines/${routineId}` : '/'

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      const existing = windowClients.find((c) => c.url.startsWith(self.location.origin))
      if (existing) {
        existing.navigate(url)
        return existing.focus()
      }
      return clients.openWindow(url)
    })
  )
})
