import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'

// Remove caches from older Workbox versions that are no longer needed.
cleanupOutdatedCaches()

// Precache all assets generated by Vite (injected by vite-plugin-pwa at build time).
precacheAndRoute(self.__WB_MANIFEST)

// SPA navigation fallback: every navigation request (user typing a URL,
// React Router navigating to /settings, /history, etc.) resolves to the
// precached index.html. Without this, offline reloads of deep links
// fail with net::ERR_FAILED because the URL has no server-side route.
registerRoute(new NavigationRoute(createHandlerBoundToURL('/index.html')))

// ── Runtime caching for /api/ GETs ───────────────────────────────────────────
// NetworkFirst: go to network with a short timeout; on failure (offline or
// slow link) serve the last cached 200 OK. Lets the dashboard, inventory,
// history, etc. render offline after they've been visited at least once.
// POST/PATCH/DELETE are explicitly excluded — those go through the offline
// mutation queue in offline/sync.js.
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'nudge-api-cache',
    networkTimeoutSeconds: 4,
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  }),
)

// ── Runtime caching for app assets (dev-mode E2E) ───────────────────────────
// In a production build, `precacheAndRoute(self.__WB_MANIFEST)` above feeds
// the precache with every built script/style/image, so an offline reload
// is served from there. In dev mode, __WB_MANIFEST is empty — Vite serves
// modules on-the-fly — so an offline reload cannot load the React app.
// This NetworkFirst rule shadows the empty precache in dev by caching
// same-origin assets as they're first served online. Harmless in
// production (precache matches first).
registerRoute(
  ({ url, request, sameOrigin }) =>
    sameOrigin &&
    !url.pathname.startsWith('/api/') &&
    (request.destination === 'script' ||
      request.destination === 'style' ||
      request.destination === 'document' ||
      request.destination === 'image' ||
      request.destination === 'font' ||
      request.mode === 'navigate'),
  new NetworkFirst({
    cacheName: 'nudge-app-assets',
    networkTimeoutSeconds: 4,
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  }),
)

// ── Background Sync ──────────────────────────────────────────────────────────
// When the browser signals a sync event for our tag (registered from the main
// thread on every enqueue), we don't drain the queue from the SW — the queue
// lives in IndexedDB and requires the app's auth context. Instead we post a
// message to every open client so offline/sync.js can process it there. This
// path fires in Chromium when the browser detects recovered connectivity
// (even without an open tab). On browsers without Background Sync the main
// thread's `online` listener covers the case.
self.addEventListener('sync', (event) => {
  if (event.tag !== 'nudge-offline-queue') return
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      clients.forEach((client) => client.postMessage({ type: 'PROCESS_QUEUE' }))
    }),
  )
})

// ── Push notifications ────────────────────────────────────────────────────────

self.addEventListener('push', (event) => {
  let data = {}
  try {
    data = event.data?.json() ?? {}
  } catch {
    console.error('[SW] Push data parse error:', event.data?.text())
  }
  const title = data.title ?? 'Nudge'
  const options = {
    body: data.body ?? '',
    icon: '/icons/pwa-192x192.png',
    badge: '/icons/badge.svg',
    tag: data.data?.routine_id ? `${data.type}-${data.data.routine_id}` : data.type,
    renotify: true,
    data: data.data ?? {},
    actions: data.actions ?? [],
  }
  // Broadcast a copy of the push to every open client so the app (and E2E
  // tests) can observe arrivals without hooking into notificationclick.
  // The payload shape mirrors what the backend sent in push.py.
  const broadcast = self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
    clients.forEach((client) => client.postMessage({ type: 'push-received', payload: { title, ...data } }))
  })
  event.waitUntil(Promise.all([self.registration.showNotification(title, options), broadcast]))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const routineId = event.notification.data?.routine_id
  const url =
    event.action === 'mark-done' && routineId
      ? `/routines/${routineId}?action=mark-done`
      : routineId
        ? `/routines/${routineId}`
        : '/'

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      const existing = windowClients.find((c) => c.url.startsWith(self.location.origin))
      if (existing) {
        existing.navigate(url)
        return existing.focus()
      }
      return clients.openWindow(url)
    }),
  )
})
