import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'

// Remove caches from older Workbox versions that are no longer needed.
cleanupOutdatedCaches()

// Precache all assets generated by Vite (injected by vite-plugin-pwa at build time).
precacheAndRoute(self.__WB_MANIFEST)

// ── Push notifications ────────────────────────────────────────────────────────

self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {}
  const title = data.title ?? 'Nudge'
  const options = {
    body: data.body ?? '',
    icon: '/icons/pwa-192x192.png',
    badge: '/icons/badge.svg',
    data: data.data ?? {},
    actions: data.actions?.length
      ? data.actions
      : [
          { action: 'mark-done', title: 'Mark as done' },
          { action: 'dismiss', title: 'Dismiss' },
        ],
  }
  event.waitUntil(self.registration.showNotification(title, options))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const routineId = event.notification.data?.routine_id

  if (event.action === 'mark-done' && routineId) {
    // Open the routine page with action param — the page will auto-log
    event.waitUntil(clients.openWindow(`/routines/${routineId}?action=mark-done`))
  } else {
    event.waitUntil(clients.openWindow(routineId ? `/routines/${routineId}` : '/'))
  }
})
